### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jmduarte**
- [x] format code with black
- [x] add pre-commit config
- [ ] add github action to run pre-commit config
- [ ] remove code duplication in different dataForge versions (maybe ask @drankincms or @aidan-dc why we need these different versions first)
- [ ] remove ROOT files (but maybe commit somewhere else for running automated testing)
- [ ] separate seeded cone jet algorithm into separate python function/class (and re-use)

@ddiaz006 @jhchoi212 @AnthonyAportela

### CODE REVIEW

**Comment by aidan-dc** [comment]
Hi @jmduarte, the separate dataForge versions are made for three slightly different purposes:

1. dataForge.py is the original script that performs a near identical process to seeded cone jet reconstruction and stores the N recreated jets in a (N,) shape array.
2. dataForgeEvent.py repeats the jet reconstruction process but stores jets into a 2D array, grouping reconstructed jets from the events they were taken from.
3. dataForgeHH4b.py accomplishes a similar task to dataForgeEvent.py but for the nuances of our training with GluGlu->HH->4b events, it includes conditions to remove any events that lack 4 gen b quarks with pT>30 GeV.

Data forge scripts 2 and 3 are primarily used just for rates studies from our applications of b tagging in the HH4b channel. If the goal here is just to create datasets for training and testing a b tagging network then script 1 dataForge.py should be the only one you need. Although if it would be helpful to also group jets based on the event they were reconstructed from, I'd be happy to update dataForge.py to include a parameter to specify if jets are stored in a 1D or 2D list, effectively combining scripts 1 and 2.

**Comment by jmduarte** [comment]
hi @aidan-dc, thanks for the comments! Yes, I think it makes sense to merge the scripts into 1 (or at least factorize the common parts of the code into a separate function/class/file).

We can try to work on that. 

I also had another question maybe for @Duchstf or @drankincms... Where is the latest model code that is actually planned to be used in the trigger?

Thanks!

**Comment by Duchstf** [comment]
@jmduarte So I have some of my experiments to scale down to a smaller model saved here:

https://github.com/Duchstf/L1BTag/tree/basic_setup

The "official version" for the b-tagging model is still on correlator2, I'll clean it up and upload it once I finish testing the model on the APx setup. Or do you want me to upload a preliminary version?

**Comment by jmduarte** [comment]
@Duchstf sure, a preliminary version would be great, just to see!

**Comment by Duchstf** [comment]
@jmduarte Could you give me write permission to the repo (ucsd-hep-ex/L1JetTag) so I could push my branch?

**Comment by Duchstf** [comment]
@jmduarte Nevermind I backed up a version here: 

https://github.com/Duchstf/L1BTag/tree/basic_setup/hls4ml_conversion/L1B_v9

**Comment by jmduarte** [comment]
added you anyway!

**Pull request merged**
